HW DE COMPUTADORA:

ES TODO EQUIPO FISICO NECESARIO PARA EJECUTAR (PERFORMANCE) INSTRUCCIONES DE COMPUTADORA

ELEMENTOS DEL HW

-CPU: CENTRAL PROCESING UNIT
-RAM: RANDOM ACCESS MEMORY
-HDD: HARD DISK DRIVE
-I/O: TODO LO DEMÁS

PERFORMANCE(I/O)= HDD * RAM * CPU * #P * #N


SW: SOLO EXISTEN 2 TIPOS DE SOFTWARE

- SISTEMA OPERATIVO

SON LOS PROGRAMAS QUE LE DICEN AL HARDWARE QUE HACER Y COMO HACERLO

LAYERS (CAPAS DE S.O.)

- KERNELL: NUCLEO QUE GESTIONA Y ADMINISTRA LOS PROCESOS DEL CPU (GESTIONAR ES PEDIR-ADMINISTRAR ES MANDAR)
- SHELL: ES EL INTERPRETE DE COMMANDOS
- FILE SYSTEM: ES EL FILE MANAGER
- GRAPHICAL USER INTERFASE (GUI): ES LO QUE VEMOS

- APPs O PLATTFORMS

	SON CONJUNTOS DE PROGRAMAS CON UN FIN EN COMUN